@URL=https://api.test.danielcooper.io

POST {{URL}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "targetLang": "es",
    "sourceLang": "en",
    "text": "Hello, my name is Daniel!"
}

###

GET {{URL}} HTTP/1.1
Content-Type: application/json
Accept: application/json
